st = (input("Give me a first number: "))
sec = (input("Give me a second number: "))
int_st = int(st)
int_sec = int(sec)
print("Thank you")
print(f"{int_st} + {int_sec} = {int_st + int_sec}")
print(f"{int_st} - {int_sec} = {int_st - int_sec}")
print(f"{int_st} * {int_sec} = {int_st * int_sec}")
print(f"{int_st} / {int_sec} = {int_st / int_sec}")