your_age = input("Please tell me your age: ")
int_age = int(your_age)
print(f"You are currently {int_age} years old.")
print(f"In 10 years, you'll be {int_age+10} years old.")
print(f"In 20 years, you'll be {int_age+20} years old.")
print(f"In 30 years, you'll be {int_age+30} years old.")